### ISSUE TITLE
Add a panel for browsing through aircraft

### ISSUE THREAD

**Issue by Azekthi** [agc93/acevortex#4] opened 2020-08-24 09:56 UTC
Below the "Mods" panel, it would be helpful to have another panel, something like "Aircraft" or "Skins", that lists all of the aircraft and their skins and display which ones are modded, and by which mods, and which ones are not modded.

The only thing is, this would probably need https://github.com/agc93/acevortex/blob/master/src/attributes/attributes.ts to be updated to support DLC skin slots.

**Comment by agc93** [comment] 2020-08-25 02:42
Thanks for another great suggestion @Azekthi ! 

I've had a look at this previously and there's a few things that make this a bit difficult to implement without a significant change to how we handle skin detection. Then again, I've made a few big changes since I tried that out so I will give it another shot.

I'll give this a try, but no guarantees!

**Comment by Azekthi** [comment] 2020-08-25 02:48
Yeah, that makes sense. The data would have to be stored somewhere outside of just the text field in the installed mod. It's no big issue, but it would be supremely helpful to have a single place to see all of it, outside of just launching the game xD

**Comment by Azekthi** [comment] 2020-09-21 13:04
Couple of things now that 0.2.0 is out:

- Thank goodness, indeed all of the skins I had installed are now properly detected! Except... just one, right now. [Gripen E -Wisna-](https://www.nexusmods.com/acecombat7skiesunknown/mods/589) comes with two files, one for the MREC and one for the livery. Both need to be installed so the proper camo pattern appears in all lighting conditions, but the skin detection in acevortex is seeing this as two skins in the same mod slot. In my example, I've installed them on the Erusea skin.

![image](https://user-images.githubusercontent.com/11371137/93769786-53cb3700-fbe9-11ea-830e-374ebe366767.png)

- NPC skins are also showing. Is this intentional? If so, maybe we could set this up a little better, like pushing them to the bottom of this list?

![image](https://user-images.githubusercontent.com/11371137/93769876-73625f80-fbe9-11ea-971a-10034b4b04a7.png)

**Comment by agc93** [comment] 2020-09-22 01:43
Huh. Never seen a mod distribute the MREC as a separate file. I can fix that up by just ignoring MRECs for now.

As for NPCs, that is intentional, but I'm probably going to make it either a) a toggle or b) a separate section

**Comment by agc93** [comment] 2020-09-23 15:17
@Azekthi Alright version 0.2.1 has made its way through the process and should be available now. 

All [the details are in the release notes](https://ac7.vortex.support/updates/v0.2.1/) but the Gripen situation should be fixed and I've tweaked the Skins view to push NPCs to the bottom and allow toggling them off entirely (purely a visual toggle)

**Comment by Azekthi** [comment] 2020-09-24 10:03
Doing good, doing good! We're almost there :D

I've got a few remaining mods where the skins aren't being detected:

- https://www.nexusmods.com/acecombat7skiesunknown/mods/159
- https://www.nexusmods.com/acecombat7skiesunknown/mods/379
- https://www.nexusmods.com/acecombat7skiesunknown/mods/380
- https://www.moddb.com/games/ace-combat-7/addons/su-30m2-experimental

And I've also got this mod adding a new aircraft to the Skins page: "W" https://www.nexusmods.com/acecombat7skiesunknown/mods/453/

Other than these, and the one thing about the NPC toggle not saving between Vortex sessions (maybe change it to a setting?) I think it's looking good :D

**Comment by agc93** [comment] 2020-09-24 11:26
I'll look into those mods, but I will say that we might never get to 100%. The detection is just supposed to be an extra safeguard against someone installing two skins in the same slot, and we're already having to do some hacky shit to read them as-is.

> Other than these, and the one thing about the NPC toggle not saving between Vortex sessions (maybe change it to a setting?) I think it's looking good :D

That's a deliberate choice. I don't want people toggling it off, forgetting about it, and thinking their NPC skins aren't being picked up. If I get any more feedback about that and/or requesting it be persisted, I'll change it over.

**Comment by agc93** [comment] 2020-09-24 11:50
and sure enough, we've found the "never reach 100%" mark: that Avril F-104 skin is packed with an **extremely** old method and handling how its done would break detection for a big chunk of other mods.

The weapon mod being identified is definitely a bug but I can fix that up easy enough. As for those Oryol, Stalker and Experimental skins, they all work fine for me. Can you Refresh Skins on those mods and see if it picks it up? The skins are only detected on first install so after that you need to manually refresh them.

**Comment by Azekthi** [comment] 2020-09-25 05:37
> I will say that we might never get to 100%

Oh, of course not, there will definitely be edge cases, especially old skins. Doesn't surprise me that that mod, how old it is, isn't working. No worries!

I'm curious if we might be able to have a manual override for the skins? It might help for the skin organization in the Skins page.

> That's a deliberate choice. I don't want people toggling it off, forgetting about it, and thinking their NPC skins aren't being picked up.

Ah, fair enough!

> As for those Oryol, Stalker and Experimental skins, they all work fine for me. Can you Refresh Skins on those mods and see if it picks it up? The skins are only detected on first install so after that you need to manually refresh them.

I only reported them because Refresh Skins isn't working for these mods.

**Comment by agc93** [comment] 2020-09-25 07:21
> I'm curious if we might be able to have a manual override for the skins? It might help for the skin organization in the Skins page.

It's not planned at this time (that would be quite a bit of work and would be very easy for a user to get wrong with how its currently designed), but as always if I get more feedback/demand I'll add it to the backlog.

> > As for those Oryol, Stalker and Experimental skins, they all work fine for me. Can you Refresh Skins on those mods and see if it picks it up? The skins are only detected on first install so after that you need to manually refresh them.
> 
> I only reported them because Refresh Skins isn't working for these mods.

Okay can you raise a separate issue for those then and include links to mod reports (right click mod in Mods list > Create Report > Share) for whichever ones aren't working? I can't reproduce it on my end (they get picked up just fine) so will need to investigate them separately.

**Closed** 2020-09-25 10:12 UTC
